name: Build and deploy two documentation sites

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  DOCKER_VERSION: '242.21870'

jobs:
  build-Woo7Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Woo7Docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: 'Writerside/ddotdocs'
          artifact: 'webHelpDDOTDOCS2-all.zip'
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save Woo7Docs build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Woo7Docs
          path: |
            artifacts/webHelpDDOTDOCS2-all.zip
            artifacts/report.json
          retention-days: 7

  build-Not-Yet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Not-Yet using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: 'Writerside/ul'
          artifact: 'webHelpUL2-all.zip'
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save Not-Yet build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Not-Yet
          path: |
            artifacts/webHelpUL2-all.zip
            artifacts/report.json
          retention-days: 7

  deploy:
    needs: [build-Woo7Docs, build-Not-Yet]
    runs-on: ubuntu-latest
    steps:
      - name: Download Woo7Docs artifacts
        uses: actions/download-artifact@v4
        with:
          name: Woo7Docs

      - name: Download Not-Yet artifacts
        uses: actions/download-artifact@v4
        with:
          name: Not-Yet

      - name: Unzip Woo7Docs artifact
        run: unzip -O UTF-8 -qq 'artifacts/webHelpDDOTDOCS2-all.zip' -d Woo7Docs

      - name: Unzip Not-Yet artifact
        run: unzip -O UTF-8 -qq 'artifacts/webHelpUL2-all.zip' -d Not-Yet

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Package and upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            Woo7Docs  # Woo7Docs 경로
            Not-Yet  # Not-Yet 경로

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
