name: Build and deploy Woo7Docs and Not-Yet

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  DOCKER_VERSION: '242.21870'

jobs:
  build-site1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for site1
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Woo7Docs using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: 'Writerside/ddotdocs'
          artifact: 'webHelpDDOTDOCS2-all.zip'
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save Woo7Docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-site1
          path: |
            artifacts/webHelpDDOTDOCS2-all.zip
            artifacts/report.json
          retention-days: 7

  build-site2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for site2
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Not-Yet using Writerside Docker builder
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: 'Writerside/ul'
          artifact: 'webHelpUL2-all.zip'
          docker-version: ${{ env.DOCKER_VERSION }}

      - name: Save Not-Yet artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-site2
          path: |
            artifacts/webHelpUL2-all.zip
            artifacts/report.json
          retention-days: 7

  test-site1:
    needs: build-site1
    runs-on: ubuntu-latest
    steps:
      - name: Download Woo7Docs artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-site1

      - name: Test Woo7Docs documentation
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: 'Writerside/ddotdocs'

  test-site2:
    needs: build-site2
    runs-on: ubuntu-latest
    steps:
      - name: Download Not-Yet artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-site2

      - name: Test Not-Yet documentation
        uses: JetBrains/writerside-checker-action@v1
        with:
          instance: 'Writerside/ul'

  deploy:
    needs: [test-site1, test-site2]
    runs-on: ubuntu-latest
    steps:
      - name: Download Woo7Docs artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-site1

      - name: Download Not-Yet artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs-site2

      - name: Unzip Woo7Docs artifact
        run: unzip -O UTF-8 -qq 'artifacts/webHelpDDOTDOCS2-all.zip' -d Woo7Docs

      - name: Unzip Not-Yet artifact
        run: unzip -O UTF-8 -qq 'artifacts/webHelpUL2-all.zip' -d Not-Yet

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Package and upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: |
            Woo7Docs  # Woo7Docs
            Not-Yet  # Not-Yet

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
